import type { NextConfig } from 'next';
const config: NextConfig = {
  poweredByHeader: false, serverExternalPackages: ['pg'],
  agentRules: false, // Project authority is maintained in AGENTS.md, not generated by the dev server.
};
export default config;
